colors:
  background_color: '1a1b26'
  white: '828997'
  red: 'f7768e'
  green: '9ece6a'
  yellow: 'e0af68'
  blue: '3d59a1'
  pink: 'bb9af7'
  cyan: '7dcfff'

  black: '414868'
  gray: '565f89'
  darkgray: '545c7e'
  darkergray: '737aa2'

core:
  regular_file: {}

  directory:
    foreground: blue

  executable_file:
    foreground: red
    font-style: bold

  symlink:
    foreground: pink

  broken_symlink:
    foreground: black
    background: red
  missing_symlink_target:
    foreground: black
    background: red

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: pink

  character_device:
    foreground: pink
    background: darkergray

  block_device:
    foreground: cyan
    background: darkergray

  normal_text:
    {}

  other_writable:
    {}

  sticky:
    {}

  sticky_other_writable:
    {}

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink

office:
  foreground: red

archives:
  foreground: cyan
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: darkgray
