- name: Run aditional tasks
  hosts: localhost
  connection: local
  vars_files:
    - '{{ root }}/requirements.yml'
  tasks:
    - include_tasks: ./tasks/kubectl-directories.yml
    - include_tasks: ./tasks/lua-language-server.yml
    - include_tasks: ./tasks/docker-completions.yml
    - include_tasks: ./tasks/vscode-chrome-debug.yml
    - include_tasks: ./tasks/vscode-node-debug2.yml
    - include_tasks: ./tasks/ansible-language-server.yml
